// ================= GAME VARIABLES =================

let started = false; 
// The keypress event listener starts the game only once at the beginning.
// When the first key is pressed, started becomes true, so further keypresses do not restart the game again and again.

// Array that stores the sequence generated by the game
let gameSeq = [];

// Array that stores the sequence clicked by the user
let userSeq = [];

// Level counter
level = 0;

// Available button colors in the game
let btns = ["yellow", "red", "purple", "green"];

// Selecting the <h2> element where level / game messages will be displayed
let h2 = document.querySelector("h2");


// ================= START GAME =================

// Listen for any keypress on the document
document.addEventListener("keypress", function() {

    // Game should start only if it has not started already
    if(started === false) {

        // Print in console (for debugging)
        console.log("Game started");

        // Change flag so game doesn't restart again with another keypress
        started = true;

        // Start the first level
        levelUp();
    }
})




// ================= LEVEL UP FUNCTION =================

function levelUp() {

    // Reset user sequence for the new level
    userSeq = [];

    // Print in console
    console.log("Level up");

    // Increase level
    level++;

    // Show updated level in UI
    h2.innerText = `Level ${level}`;

    // Generate random index between 0–3
    let randIdx = Math.floor(Math.random() * 4);
//     Math.random() generates a random decimal number between 0 and 1.
// Multiplying by 4 changes the range to 0 – 3.999, since we have 4 buttons.
// Math.floor() removes the decimal part and rounds down to an integer.
// So the final result is a random index: 0, 1, 2, or 3.

    // Get color from btns array using random index
    let randColor = btns[randIdx];

    // Print random color in console
    console.log(randColor);

    // Select the button element of that color
    let randBtn = document.querySelector(`.${randColor}`);

    // Add that color to game sequence
    gameSeq.push(randColor);

    // Flash the randomly selected button
    btnFlash(randBtn);
}

// ================= BUTTON FLASH (GAME FLASH) =================

// Function that flashes a button when the game shows the sequence
function btnFlash(btn) {

    // Add CSS class "flash"
    btn.classList.add("flash");

    // Remove flash class after 300 milliseconds
    setTimeout(function() {
        btn.classList.remove("flash");
    }, 300);
}


// ================= USER BUTTON FLASH =================

// Function to flash button when USER clicks it
function userFlash(btn) {

  // Add class "userflash"
  btn.classList.add("userflash");

  // Remove class after 300 ms
  setTimeout(function () {
    btn.classList.remove("userflash");
  }, 300);
}


// ================= RESET GAME =================

function resetGame() {

    // Mark game as not started
    started = false;

    // Clear game sequence
    gameSeq = [];

    // Clear user sequence
    userSeq = [];

    // Reset level to 0
    level = 0; 
}


// ================= CHECK USER ANSWER =================

function checAns() {

    // Get index of last element user clicked
    let idx = userSeq.length - 1;

    // Check if user's last click matches game sequence
    if(userSeq[idx] === gameSeq[idx]) {

        // Correct click
        console.log("Success");

        // If user finished full sequence correctly
        if(userSeq.length === gameSeq.length) {

            // Move to next level after 1 second
            setTimeout(levelUp, 1000);
        }
    }

    // If user clicked wrong button
    else{

        // Show game over message
        h2.innerText = `Game over! score ${level} Press any other key to start.`

        // Reset the game
        resetGame();
    }
}


// ================= USER BUTTON PRESS =================

function btnPress(){

    // Flash the button user clicked
    userFlash(this);

    // Get color of clicked button from its id
    userColor = this.getAttribute("id");

    // Add clicked color to user sequence
    userSeq.push(userColor);

    // Check if answer is correct
    checAns();

}


// ================= ADD CLICK EVENTS TO BUTTONS =================

// Select all buttons inside .btn-container
allbtns = document.querySelectorAll('.btn-container .btn');

// Loop through each button
for(btn of allbtns) {

    // Add click event listener
    btn.addEventListener("click", btnPress);
}